name: "docker"
on:
  release:
    types: ["published"]
jobs:
  build:
    name: "Build & Push Container Image"
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v2"
    - uses: "docker/login-action@v1"
      with:
        registry: "quay.io"
        username: "${{ secrets.QUAY_USERNAME }}"
        password: "${{ secrets.QUAY_ROBOT_TOKEN }}"
    - uses: "docker/setup-buildx-action@v1"
    - uses: "docker/build-push-action@v2"
      with:
        push: true
        build-args: "VERSION=${{ github.ref }}"
        tags: |
          quay.io/authzed/zed-testserver:latest
          quay.io/authzed/zed-testserver:${{ github.ref }}
